# Generated by Django 2.1 on 2018-08-29 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180828_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Enter valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
